---
output: 
  github_document:
    html_preview: false
params: 
  actor_id: "roten" 
  data_date: "2020-03-26"
  sha: "sha"
---
## Notes  

"Regional Parks and the American Community Survey" is a mini-app designed for use by Regional Parks implementing agencies to assist in their progressing toward a more equitable use of regional parks. The app complements the [Regional Parks Equity Toolkit](https://metrocouncil.org/parks/Planning/Parks-Equity-Toolkit.aspx), a set of questions and a process to clarify how regional park projects are advancing equity. The app facilitates direct examination of regional parks and trails system and the demographic characteristics of the census tracts surrounding them.  

The Map tab displays census tracts in the Twin Cities metropolitan area. The tracts' colors correspond to 2014-2018 (5-year) American Community Survey (ACS) demographic metric selected by the user. Each demographic characteristic is shown as a percentage of the total population, with the exception of median household income, which is displayed in dollars. The darker the color, the higher the percentage (or income in dollars).    

Statistics produced for American Community Survey and included in ACS tables are survey-based estimates and are subject to error. The errors derive from research design (including instrument bias, data frame, and sampling), the survey data collection (non-response bias and response errors), and processing by the Census Bureau (data coding, compilation processes, and case weighting), as well as statistical inference error and uncertainty (which are related to sample size and variance within the measured attributes). US Census Bureau's report on "Accuracy of the Data" can be found [here](https://www2.census.gov/programs-surveys/acs/tech_docs/accuracy/MultiyearACSAccuracyofData2017.pdf?#).  

### Authors  

"Regional Parks and the American Community Survey" was developed by the Research Team at the Metropolitan Council. You can find more of our work at [metrocouncil.org/data](https://metrocouncil.org/data). Our dashboard "Visualizing Regional Racial Disparities" is available [here](https://metrocouncil.org/Data-and-Maps/Data/Reports-Resources/Featured-Visualization/Visualizing-Regional-Racial-Disparities.aspx?source=child).  

Our Principal Parks Researcher is Darcie Vandegrift, available at [darcie.vandegrift@metc.state.mn.us](mailto:darcie.vandegrift@metc.state.mn.us)  
  
For app concerns, please contact Liz Roten at [liz.roten@metc.state.mn.us](mailto:elizabeth.roten@metc.state.mn.us)  

### References  

Bibliography includes both data sources and R packages used in app development.  

  
<right style="font-size: 1rem; text-align: right; display: block;">
*Last updated `r Sys.Date()`*  
Build ID: `r Sys.Date()`.`r params$actor_id`.`r params$sha`  
</right>
